site_name: Customized Unix Terminal
docs_dir: .
site_dir: ../site
repo_url: https://github.com/StrangeRanger/customized-unix-terminal

theme:
  favicon: https://randomserver.xyz/favicon.ico
  name: material
  palette:
    scheme: slate
    primary: blue
    accent: blue
  features:
    #- navigation.tabs  # Disabled for this project
    - navigation.instant
    - navigation.sections
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

plugins:
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  - search
  - same-dir

markdown_extensions:
  # Built in extensions
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - admonition
  - meta
  - footnotes
  # Extensions provide by pymdown
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed

nav:
  - Home: README.md
  - Changelog: CHANGELOG.md
  - License: LICENSE.md
