site_name: Custom Unix Terminal
site_url: https://cut.hthompson.dev
site_author: Hunter T.
site_description: Custom configurations for Unix terminals.

repo_name: Custom Unix Terminal
repo_url: https://github.com/StrangeRanger/custom-unix-terminal

theme:
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for dark mode.
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: blue
      accent: blue
    # Palette toggle for light mode.
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: blue
      accent: blue
  features:
    # When enabled, all content tabs across the whole documentation site will be linked
    # and switch to the same label when the user clicks on a tab.
    # DOCS: https://squidfunk.github.io/mkdocs-material/reference/content-tabs/?h=content+tabs#linked-content-tabs
    - content.tabs.link
    # Code blocks can automatically render a button on the right side to allow the user
    # to copy a code block's contents to the clipboard.
    # DOCS: https://squidfunk.github.io/mkdocs-material/upgrade/?h=content+code+copy#contentcodecopy
    - content.code.copy
    # When instant loading is enabled, clicks on all internal links will be intercepted
    # and dispatched via XHR without fully reloading the page.
    # DOCS: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+instant#instant-loading
    - navigation.instant
    # When anchor tracking is enabled, the URL in the address bar is automatically
    # updated with the active anchor as highlighted in the table of contents.
    # DOCS: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+tracking#anchor-tracking
    - navigation.tracking
    # When sections are enabled, top-level sections are rendered as groups in the
    # sidebar for viewports above 1220px, but remain as-is on mobile.
    # DOCS: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+tracking#navigation-sections
    - navigation.sections
    # A back-to-top button can be shown when the user, after scrolling down, starts to
    # scroll up again. It's rendered centered and just below the header.
    # DOCS: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation#back-to-top-button
    - navigation.top
    # When search suggestions are enabled, the search will display the likeliest
    # completion for the last word which can be accepted with the Right key.
    # DOCS: https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/?h=search+suggest#search-suggestions
    - search.suggest
    # When search highlighting is enabled and a user clicks on a search result, Material
    # for MkDocs will highlight all occurrences after following the link.
    # DOCS: https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/?h=search+highlight#search-highlighting
    - search.highlight
  icon:
    annotation: material/plus-circle
    repo: fontawesome/brands/github

extra:
  analytics:
    provider: matomo

extra_css:
  - stylesheets/extra.css

plugins:
  ### Built-in plugins.
  # The built-in search plugin integrates seamlessly with Material for MkDocs, adding
  # multilingual client-side search with lunr and lunr-languages.
  # DOCS: https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/?h=search#built-in-search-plugin
  - search
  ### External plugins.
  # MkDocs plugin that enables displaying the date of the last git modification of a
  # page.
  # DOCS: https://github.com/timvink/mkdocs-git-revision-date-localized-plugin
  - git-revision-date-localized:
      type: date
      timezone: America/Los_Angeles
      fallback_to_build_date: true
      enabled: true
  # MkDocs plugin that enables a markdown tag like {{ read_csv('table.csv') }} to
  # directly insert various table formats into a page.
  # DOCS: https://github.com/timvink/mkdocs-table-reader-plugin
  - table-reader

markdown_extensions:
  # The Attribute Lists extension allows to add HTML attributes and CSS classes to
  # almost every Markdown inline- and block-level element with a special syntax.
  # DOCS: https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/?h=attr+list#attribute-lists
  - attr_list
  # The BetterEm extension improves the detection of Markup to emphasize text in
  # Markdown using special characters, i.e. for **bold** and _italic_ formatting.
  # DOCS: https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#betterem
  - pymdownx.betterem:
      smart_enable: all
  # The Admonition extension adds support for admonitions, more commonly known as
  # call-outs, which can be defined in Markdown by using a simple syntax.
  # DOCS: https://facelessuser.github.io/pymdown-extensions/extensions/blocks/plugins/admonition/
  - pymdownx.blocks.admonition
  # The Details extension supercharges the Admonition extension, making the resulting
  # call-outs collapsible, allowing them to be opened and closed by the user.
  # DOCS: https://facelessuser.github.io/pymdown-extensions/extensions/blocks/plugins/details/
  - pymdownx.blocks.details
  # The Tabbed extension allows the usage of content tabs, a simple way to group related
  # content and code blocks under accessible tabs.
  # DOCS: https://facelessuser.github.io/pymdown-extensions/extensions/blocks/plugins/tab/
  - pymdownx.blocks.tab:
      alternate_style: true
  # The Highlight extension adds support for syntax highlighting of code blocks (with
  # the help of SuperFences) and inline code blocks (with the help of InlineHilite).
  # DOCS: https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight
  # REQUIRES: 'pymdownx.superfences', 'pymdownx.inlinehilite' (for inline code blocks)
  # REQUIRED BY: 'pymdownx.inlinehilite'
  - pymdownx.highlight:
      # If a code blocks contains line numbers, enabling this setting will wrap them
      # with anchor links, so they can be hyperlinked and shared more easily.
      anchor_linenums: true
      # When this option is set, each line of a code block is wrapped in a span, which
      # is essential for features like line highlighting to work correctly.
      line_spans: __span
      # This option instructs Pygments to add a CSS class to identify the language of
      # the code block, which is essential for custom annotation markers to function.
      pygments_lang_class: true
      # This option will add line numbers to all code blocks.
      linenums: true
  # The InlineHilite extension adds support for syntax highlighting of inline code
  # blocks.
  # REQUIRES: 'pymdownx.highlight'
  # REQUIRED BY: 'pymdownx.highlight'
  # DOCS: https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#inlinehilite
  - pymdownx.inlinehilite
  # The SuperFences extension allows for arbitrary nesting of code and content blocks
  # inside each other, including admonitions, tabs, lists and all other elements.
  # REQUIRED BY: 'pymdownx.highlight'
  # DOCS: https://facelessuser.github.io/pymdown-extensions/extensions/superfences/
  - pymdownx.superfences
  # The Keys extension adds a simple syntax to allow for the rendering of keyboard keys
  # and combinations.
  # DOCS: https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#keys
  - pymdownx.keys
  # The SmartSymbols extension converts some sequences of characters into their
  # corresponding symbols, e.h. copyright symbols or fractions.
  # DOCS: https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#smartsymbols
  - pymdownx.smartsymbols
  # The Snippets extension adds the ability to embed content from arbitrary files into a
  # document, including other documents or source files, by using a simple syntax.
  # DOCS: https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#snippets
  - pymdownx.snippets

nav:
  - Home: index.md
  - Changelog: changelog.md
  - License: license.md
