"""Configuration for the repository update automation.

The update script generates documentation includes from files in the dotfiles
submodule. This module keeps the brittle, repository-specific details in one
place: source/destination paths, section markers, and the render jobs that tie
those pieces together.

NOTE: This module was rewritten with Codex.
"""

from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Final


class RenderKind(str, Enum):
    """Supported ways to generate an include file."""

    COPY = "copy"
    EXTRACT_SECTION = "extract_section"
    ZSH_FULL = "zsh_full"
    ZSH_SNIPPET = "zsh_snippet"


@dataclass(frozen=True)
class ConfigPath:
    """Source and destination paths for one generated file."""

    src: Path
    dest: Path


@dataclass(frozen=True)
class SectionMarker:
    """Text markers that bound a generated section."""

    start_marker: str
    end_marker: str
    hard_coded_inclusion: tuple[str, ...] = ()


@dataclass(frozen=True)
class RenderJob:
    """One configured output generated by update_repo.py."""

    name: str
    paths: ConfigPath
    kind: RenderKind
    section: SectionMarker | None = None


@dataclass(frozen=True)
class SnippetSection:
    """Mapping from a source section to its Zensical wrapper markers."""

    source: SectionMarker
    wrapper: SectionMarker


# Section markers for the general configuration section in ``init.vim``.
NEOVIM_MARKERS: Final[SectionMarker] = SectionMarker(
    start_marker='""""[ General Configurations ]',
    end_marker='""""[ vim-plug Plugin Configurations ]',
)

# Section markers for the aliases portion of the generated zshrc.
ZSH_ALIAS_MARKERS: Final[SectionMarker] = SectionMarker(
    start_marker="####[ Aliases ]",
    end_marker="####[ Environmental Variables ]",
)

# Section markers for extracting/injecting the LS_COLORS related lines.
ZSH_LS_COLORS_MARKERS: Final[SectionMarker] = SectionMarker(
    start_marker="# Modifies the colors",
    end_marker="## Set default",
    hard_coded_inclusion=(
        "# Set list-colors to enable filename colorizing.\n",
        "zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}\n",
    ),
)

# Zensical markers used to wrap generated snippets.
ZENSICAL_USER_CONFIG_MARKERS: Final[SectionMarker] = SectionMarker(
    start_marker="# --8<-- [start:user_config]\n",
    end_marker="# --8<-- [end:user_config]\n",
)

ZENSICAL_LS_COLORS_MARKERS: Final[SectionMarker] = SectionMarker(
    start_marker="# --8<-- [start:ls_colors]\n",
    end_marker="# --8<-- [end:ls_colors]\n",
)

ZSH_SNIPPET_SECTIONS: Final[tuple[SnippetSection, ...]] = (
    SnippetSection(
        source=ZSH_ALIAS_MARKERS,
        wrapper=ZENSICAL_USER_CONFIG_MARKERS,
    ),
    SnippetSection(
        source=ZSH_LS_COLORS_MARKERS,
        wrapper=ZENSICAL_LS_COLORS_MARKERS,
    ),
)

NEOVIM_JOBS: Final[tuple[RenderJob, ...]] = (
    RenderJob(
        name="init_vim_plug",
        paths=ConfigPath(
            src=Path("submodules/dotfiles/private_dot_config/nvim/init.vim"),
            dest=Path("includes/neovim-init-files/neovim-init-vim-plug.vim"),
        ),
        kind=RenderKind.COPY,
    ),
    RenderJob(
        name="init_vim_no_plug",
        paths=ConfigPath(
            src=Path("submodules/dotfiles/private_dot_config/nvim/init.vim"),
            dest=Path("includes/neovim-init-files/neovim-init-non-vim-plug.vim"),
        ),
        kind=RenderKind.EXTRACT_SECTION,
        section=NEOVIM_MARKERS,
    ),
)

ZSH_JOBS: Final[tuple[RenderJob, ...]] = (
    RenderJob(
        name="zshrc_linux",
        paths=ConfigPath(
            src=Path("submodules/dotfiles/.chezmoitemplates/zshrc_linux.tmpl"),
            dest=Path("includes/zshrc-files/zshrc-linux.zsh"),
        ),
        kind=RenderKind.ZSH_FULL,
    ),
    RenderJob(
        name="zshrc_linux_snippet",
        paths=ConfigPath(
            src=Path("submodules/dotfiles/.chezmoitemplates/zshrc_linux.tmpl"),
            dest=Path("includes/zshrc-files/zshrc-linux-snippet.zsh"),
        ),
        kind=RenderKind.ZSH_SNIPPET,
    ),
    RenderJob(
        name="zshrc_macos",
        paths=ConfigPath(
            src=Path("submodules/dotfiles/.chezmoitemplates/zshrc_darwin.tmpl"),
            dest=Path("includes/zshrc-files/zshrc-macos.zsh"),
        ),
        kind=RenderKind.ZSH_FULL,
    ),
    RenderJob(
        name="zshrc_macos_snippet",
        paths=ConfigPath(
            src=Path("submodules/dotfiles/.chezmoitemplates/zshrc_darwin.tmpl"),
            dest=Path("includes/zshrc-files/zshrc-macos-snippet.zsh"),
        ),
        kind=RenderKind.ZSH_SNIPPET,
    ),
)
